In [2]:
import numpy as np
x = np.array([-1.7,  1.7,  1.4,  1.0,  0.0])
w = np.array([[-1.6, -1.6, -1.4, -1.7,  0.3],
              [ 0.1, -0.5, -1.0, -0.8, -1.8],
              [ 1.7, -0.1, -0.7,  0.5,  1.9]])
b = np.array([1.9, -0.1, 1.5])
x @ w.T + b

array([-1.76, -3.32, -2.04])

In [5]:
def sigmoid(z: np.ndarray) -> np.ndarray:
    """Sigmoid function.

    Parameters:
        z: the input

    Returns:
        the sigmoid of the input
    """
    # TODO: implement me
    return 1 / (1 + np.exp(-z))
x = np.array([0.9])
sigmoid(x) * (1-sigmoid(x))

array([0.20550031])

In [7]:
w = np.array([[-1.1, -0.4,  1.6,  0.7],
              [ 1.7,  0.1, -1.9, -1.5],
              [-0.8,  1.8,  1.9, -1.6]])
# cats, dogs and rabbits
x = np.array([ 0.7,  1.9, -0.9, -1.4]) # label = cat
# what’s the second component of the gradient w.r.t the weight vector for dog? cross entropy
s = 0
for i in range(3):
    s += np.exp(x @ w[i, :].T)
w1 = (np.exp(x @ w[1, :].T) * x) / s
print(w1)

[ 0.60064895  1.63033287 -0.77226294 -1.20129791]


In [8]:
1 - 0.0321 -0.2369 - 0.6439

0.08709999999999996

In [12]:
x0=0.0
y0=1

x1=1.0
y1=1

x2=4.0
y2=1

x3=9.0
y3=-1

X = np.array([[x0, 1],
              [x1, 1],
              [x2, 1],
              [x3, 1]])
# weight = np.array([[w],
#                    [b]])
y = np.array([[y0],
              [y1],
              [y2],
              [y3],])
w = np.linalg.inv(X.T @ X) @ X.T @ y
print(w)

[[-0.2244898 ]
 [ 1.28571429]]


In [24]:
def sigmoid(z: np.ndarray) -> np.ndarray:
    """Sigmoid function.

    Parameters:
        z: the input

    Returns:
        the sigmoid of the input
    """
    # TODO: implement me
    return 1 / (1 + np.exp(-z))

w = [[], [], [], []]
w[0] = [0, 0]
w[1] = [-1, 2]
w[2] = [1, -2]
w[3] = [1, 2]
print(w)
for i in range(4):
    weight = np.array(w[i])
    x = np.array([1, 2])
    y = 1
    grad = -sigmoid(-y*weight.T@x)*y*x
    print("w", i+1, "norm: ",np.linalg.norm(grad))

[[0, 0], [-1, 2], [1, -2], [1, 2]]
w 1 norm:  1.118033988749895
w 2 norm:  0.10604747631732328
w 3 norm:  2.1300205011824667
w 4 norm:  0.014965669629973236
